/*
 * File: app/view/NewRun.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Admin.view.NewRun', {
    extend: 'Ext.window.Window',
    alias: 'widget.newrun',

    requires: [
        'Admin.view.NewRunViewModel',
        'Admin.view.NewRunViewController',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.form.Panel',
        'Ext.form.Label',
        'Ext.form.field.Date',
        'Ext.form.field.ComboBox',
        'Ext.form.field.TextArea',
        'Ext.form.field.Hidden'
    ],

    controller: 'newrun',
    viewModel: {
        type: 'newrun'
    },
    height: 510,
    id: 'NewRunWindow',
    margin: 5,
    padding: 5,
    width: 429,
    title: 'New Run',
    defaultListenerScope: true,

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'button',
                    handler: 'OnSaveButtonClick',
                    icon: '/images/save.png',
                    text: 'Save',
                    scope: 'controller'
                },
                {
                    xtype: 'button',
                    handler: function(button, e) {
                        this.up('window').close();
                    },
                    icon: '/images/delete.png',
                    text: 'Cancel'
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'form',
            id: 'NewRunForm',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'container',
                    padding: 0,
                    layout: 'column',
                    items: [
                        {
                            xtype: 'textfield',
                            columnWidth: 0.5,
                            width: 159,
                            fieldLabel: 'Run ID',
                            labelWidth: 75,
                            name: 'RaceID'
                        },
                        {
                            xtype: 'label',
                            columnWidth: 0.5,
                            html: '&nbsp;   (Leave Blank for Automatic #)',
                            text: ''
                        }
                    ]
                },
                {
                    xtype: 'container',
                    padding: 0,
                    layout: 'column',
                    items: [
                        {
                            xtype: 'label',
                            html: '&nbsp;'
                        }
                    ]
                },
                {
                    xtype: 'datefield',
                    id: 'newRunRaceDateid',
                    fieldLabel: 'Run Date:',
                    labelWidth: 75,
                    name: 'RaceDate'
                },
                {
                    xtype: 'combobox',
                    width: 392,
                    fieldLabel: 'Team:',
                    labelWidth: 75,
                    name: 'TeamID',
                    displayField: 'TeamName',
                    store: 'TeamsStore',
                    valueField: 'uid',
                    listeners: {
                        select: 'onComboboxSelect'
                    }
                },
                {
                    xtype: 'combobox',
                    id: 'newRunClassid',
                    width: 392,
                    fieldLabel: 'Class:',
                    labelWidth: 75,
                    name: 'Class',
                    displayField: 'ListItem',
                    store: 'ClassStore',
                    valueField: 'IntValue'
                },
                {
                    xtype: 'combobox',
                    width: 392,
                    fieldLabel: 'Status:',
                    labelWidth: 75,
                    name: 'Status',
                    displayField: 'ListItem',
                    store: 'RunStatusStore',
                    valueField: 'IntValue'
                },
                {
                    xtype: 'textareafield',
                    height: 156,
                    width: 392,
                    fieldLabel: 'Notes:',
                    labelWidth: 75,
                    name: 'Notes'
                },
                {
                    xtype: 'hiddenfield',
                    anchor: '100%',
                    id: 'NewRunSession',
                    fieldLabel: 'Label',
                    name: 'SID'
                }
            ]
        }
    ],
    listeners: {
        afterrender: 'onWindowAfterRender'
    },

    onComboboxSelect: function(combo, record, eOpts) {
        Ext.getCmp('newRunClassid').setValue(record.get('Class'));
    },

    onWindowAfterRender: function(component, eOpts) {
        Ext.getCmp('newRunRaceDateid').setValue(GDate);
    }

});