/*
 * File: app/view/ParticipantsPanel.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Admin.view.ParticipantsPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.participantspanel',

    requires: [
        'Admin.view.ParticipantsPanelViewModel',
        'Admin.view.ParticipantsPanelController',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.Separator',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Column'
    ],

    controller: 'participantspanel',
    viewModel: {
        type: 'participantspanel'
    },
    height: 419,
    width: 719,
    title: 'Participants',

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'button',
                    handler: 'newParticipantButtonClick',
                    icon: '/images/add.png',
                    text: 'New Participant'
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'button',
                    icon: '/images/database_upload.png',
                    text: 'Upload Participants'
                },
                {
                    xtype: 'button',
                    icon: '/images/database_download.png',
                    text: 'Download CSV'
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'gridpanel',
            store: 'ParticipantsStore',
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'DiverID',
                    text: 'Diver Id'
                },
                {
                    xtype: 'gridcolumn',
                    width: 138,
                    dataIndex: 'DiverName',
                    text: 'Diver Name'
                },
                {
                    xtype: 'gridcolumn',
                    width: 153,
                    dataIndex: 'TeamName',
                    text: 'Team Name'
                },
                {
                    xtype: 'gridcolumn',
                    flex: 1,
                    dataIndex: 'StatusText',
                    text: 'Status Text'
                }
            ]
        }
    ]

});