/*
 * File: app/view/ParticipantsPanelController.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Admin.view.ParticipantsPanelController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.participantspanel',

    newParticipantButtonClick: function(button, e) {
        Ext.create('Admin.view.NewParticipant').show();
    },

    uploadParticpantsButtonClicked: function(button, e) {
        Ext.Msg.show({
            title: 'Upload Participants?',
            message: 'Are you sure you want to upload new a new participant csv file?  This will delete all of the current Participants, Teams, Runs, Run History, Diver History and create a blank database!!  This cannot be undone!!  Be sure you want to do this!!',
            buttons: Ext.Msg.YESNO,
            icon: Ext.Msg.WARNING,
            fn: function(btn) {
                if (btn === 'yes') {
                    Ext.create('Admin.view.UploadParticipants').show();
                }
            }
        });
    },

    downloadParticipantCSVButtonClicked: function(button, e) {

    }

});
