/*
 * File: app/view/ViewParticipant.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Admin.view.ViewParticipant', {
    extend: 'Ext.window.Window',
    alias: 'widget.viewparticipant',

    requires: [
        'Admin.view.ViewParticipantViewModel',
        'Admin.view.ViewParticipantViewController',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.form.FieldSet',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Hidden',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Column'
    ],

    controller: 'viewparticipant',
    viewModel: {
        type: 'viewparticipant'
    },
    height: 452,
    id: 'ViewParticipantWindow',
    margin: 5,
    padding: 5,
    width: 842,
    layout: 'column',
    title: 'View / Edit  Diver',

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'button',
                    handler: 'onSaveButtonClick',
                    icon: '/images/save.png',
                    text: 'Save'
                },
                {
                    xtype: 'button',
                    handler: function(button, e) {
                        this.up('window').close();
                    },
                    icon: '/images/delete.png',
                    text: 'Cancel'
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'fieldset',
            columnWidth: 0.38,
            title: 'Details',
            items: [
                {
                    xtype: 'form',
                    id: 'viewParticipantForm',
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'textfield',
                            width: 251,
                            fieldLabel: 'Name',
                            labelWidth: 75,
                            name: 'DiverName'
                        },
                        {
                            xtype: 'textfield',
                            width: 251,
                            fieldLabel: 'Diver ID',
                            labelWidth: 75,
                            name: 'DiverID'
                        },
                        {
                            xtype: 'combobox',
                            fieldLabel: 'Team:',
                            labelWidth: 75,
                            name: 'TeamID',
                            displayField: 'TeamName',
                            store: 'TeamsStore',
                            valueField: 'uid'
                        },
                        {
                            xtype: 'combobox',
                            fieldLabel: 'Status:',
                            labelWidth: 75,
                            name: 'Status',
                            displayField: 'ListItem',
                            store: 'DiverStatusStore',
                            valueField: 'IntValue'
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            id: 'viewParticipantSession',
                            name: 'SID'
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            fieldLabel: 'Label',
                            name: 'uid'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            columnWidth: 0.04,
            html: '&nbsp;'
        },
        {
            xtype: 'gridpanel',
            columnWidth: 0.58,
            scrollable: 'both',
            title: 'Diver Activity',
            store: 'ParticipantHistoryStore',
            columns: [
                {
                    xtype: 'gridcolumn',
                    width: 142,
                    dataIndex: 'Timestamp',
                    text: 'Timestamp'
                },
                {
                    xtype: 'gridcolumn',
                    flex: 1,
                    dataIndex: 'ActionText',
                    text: 'Action Text'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'TrackedTime',
                    text: 'Tracked Time'
                }
            ]
        }
    ],
    listeners: {
        loadRecord: 'onWindowLoadRecord'
    },

    onSaveButtonClick: function(button, e, eOpts) {

    }

});