/*
 * File: app/view/MyWindow.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.mywindow',

    requires: [
        'MyApp.view.MyWindowViewModel',
        'Ext.form.Panel',
        'Ext.form.FieldContainer',
        'Ext.form.field.ComboBox',
        'Ext.button.Button',
        'Ext.toolbar.Toolbar'
    ],

    viewModel: {
        type: 'mywindow'
    },
    autoShow: true,
    height: 638,
    padding: 5,
    width: 654,
    title: 'Edit Course Details',

    items: [
        {
            xtype: 'textfield',
            width: 350,
            fieldLabel: 'Course Name'
        },
        {
            xtype: 'textfield',
            width: 350,
            fieldLabel: 'Address 1'
        },
        {
            xtype: 'textfield',
            width: 350,
            fieldLabel: 'Address 2'
        },
        {
            xtype: 'form',
            bodyPadding: 10,
            title: ''
        },
        {
            xtype: 'fieldcontainer',
            height: 40,
            width: 654,
            layout: 'column',
            fieldLabel: 'City, St Zip',
            items: [
                {
                    xtype: 'textfield',
                    columnWidth: 0.45,
                    fieldLabel: ''
                },
                {
                    xtype: 'container',
                    columnWidth: 0.05,
                    html: '&nbsp;'
                },
                {
                    xtype: 'textfield',
                    columnWidth: 0.15,
                    width: 72,
                    fieldLabel: ''
                },
                {
                    xtype: 'container',
                    columnWidth: 0.05,
                    html: '&nbsp;'
                },
                {
                    xtype: 'textfield',
                    columnWidth: 0.28,
                    width: 164,
                    fieldLabel: ''
                }
            ]
        },
        {
            xtype: 'textfield',
            width: 350,
            fieldLabel: 'Main Phone'
        },
        {
            xtype: 'textfield',
            width: 350,
            fieldLabel: 'Booking Phone'
        },
        {
            xtype: 'textfield',
            width: 350,
            fieldLabel: 'Main Site URL'
        },
        {
            xtype: 'textfield',
            width: 350,
            fieldLabel: 'Booking URL'
        },
        {
            xtype: 'textfield',
            width: 159,
            fieldLabel: 'Holes'
        },
        {
            xtype: 'combobox',
            fieldLabel: 'Course Type'
        },
        {
            xtype: 'combobox',
            fieldLabel: 'Status'
        },
        {
            xtype: 'fieldcontainer',
            height: 40,
            width: 654,
            layout: 'column',
            fieldLabel: 'Manager',
            items: [
                {
                    xtype: 'textfield',
                    columnWidth: 0.45,
                    fieldLabel: ''
                },
                {
                    xtype: 'container',
                    columnWidth: 0.05,
                    html: '&nbsp;'
                },
                {
                    xtype: 'button',
                    text: 'Search'
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'button',
                    text: 'SAVE'
                },
                {
                    xtype: 'button',
                    text: 'CANCEL'
                }
            ]
        }
    ]

});