/*
 * File: app/view/MyWindow2.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyWindow2', {
    extend: 'Ext.window.Window',
    alias: 'widget.mywindow2',

    requires: [
        'MyApp.view.MyWindow2ViewModel',
        'Ext.grid.Panel',
        'Ext.grid.column.Date',
        'Ext.grid.column.Boolean',
        'Ext.view.Table'
    ],

    viewModel: {
        type: 'mywindow2'
    },
    height: 250,
    width: 490,
    title: 'Your Courses',

    items: [
        {
            xtype: 'gridpanel',
            title: '',
            columns: [
                {
                    xtype: 'gridcolumn',
                    flex: 1,
                    dataIndex: 'string',
                    text: 'Course Name'
                },
                {
                    xtype: 'datecolumn',
                    dataIndex: 'date',
                    text: 'Last Updated'
                },
                {
                    xtype: 'booleancolumn',
                    dataIndex: 'bool',
                    text: 'Status'
                }
            ]
        }
    ]

});