/*
 * File: app/view/MyWindow3.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyWindow3', {
    extend: 'Ext.window.Window',
    alias: 'widget.mywindow3',

    requires: [
        'MyApp.view.MyWindow2ViewModel1',
        'Ext.grid.Panel',
        'Ext.grid.column.Date',
        'Ext.grid.column.Boolean',
        'Ext.view.Table',
        'Ext.toolbar.Toolbar',
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'mywindow3'
    },
    height: 250,
    width: 657,
    title: 'Courses',

    items: [
        {
            xtype: 'gridpanel',
            title: '',
            columns: [
                {
                    xtype: 'gridcolumn',
                    flex: 1,
                    dataIndex: 'string',
                    text: 'Course Name'
                },
                {
                    xtype: 'gridcolumn',
                    flex: 0,
                    width: 141,
                    dataIndex: 'string',
                    text: 'City'
                },
                {
                    xtype: 'gridcolumn',
                    flex: 0,
                    width: 66,
                    dataIndex: 'string',
                    text: 'State'
                },
                {
                    xtype: 'datecolumn',
                    dataIndex: 'date',
                    text: 'Last Updated'
                },
                {
                    xtype: 'booleancolumn',
                    dataIndex: 'bool',
                    text: 'Status'
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'textfield',
                    fieldLabel: ''
                },
                {
                    xtype: 'button',
                    text: 'Search'
                }
            ]
        }
    ]

});