/*
 * File: app/view/DivePanelMenu.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Admin.view.DivePanelMenu', {
    extend: 'Ext.menu.Menu',
    alias: 'widget.divepanelmenu',

    requires: [
        'Admin.view.DivePanelMenuViewModel',
        'Ext.menu.Separator'
    ],

    viewModel: {
        type: 'divepanelmenu'
    },

    items: [
        {
            xtype: 'menuitem',
            handler: function(item, e) {
                //Ext.create('Admin.view.NewParticipant').show();

                var NewListwin = Ext.create('Admin.view.DiverOut');
                //NewListwin.show();
                Ext.getCmp('DiverOutSession').setValue(SID);
                Ext.getCmp('DiverOutID').setValue(selectedrec.get('DiverID'));

                var form =Ext.getCmp('DiverOutForm').getForm();

                form.submit({
                    url:'/data/actions.php',
                    params: {
                        action: 'update',
                        DiverAction: '0',
                        dataset: 'participantsWater'
                    },
                    success: function(form, action) {
                        Ext.getStore('ParticipantsInWaterStore').load();

                    },
                    failure: function(form, action) {
                        switch (action.failureType) {
                            case Ext.form.action.Action.CLIENT_INVALID:
                            Ext.Msg.alert('Failure', 'Form fields may not be submitted with invalid values');
                            break;
                            case Ext.form.action.Action.CONNECT_FAILURE:
                            Ext.Msg.alert('Failure', 'Could Not Communicate With Server.');
                            break;
                            case Ext.form.action.Action.SERVER_INVALID:
                            Ext.Msg.alert('Unable To Pull Diver Out', action.result.msg);

                        }
                    }
                });
            },
            icon: '/images/up.png',
            text: 'Diver Out'
        },
        {
            xtype: 'menuseparator',
            text: 'Menu Item'
        },
        {
            xtype: 'menuitem',
            handler: function(item, e) {
                e.stopEvent();
                var ParticipantWindow = Ext.create('Admin.view.ViewParticipant');
                ParticipantWindow.show();
                ParticipantWindow.fireEvent('loadRecord',{ID: selectedvalue});
            },
            icon: '/images/edit.png',
            text: 'View / Edit Participant'
        }
    ]

});