/*
 * File: app/view/DivePanel.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Admin.view.DivePanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.divepanel',

    requires: [
        'Admin.view.DivePanelViewModel',
        'Admin.view.DivePanelViewController',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.Separator',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Column'
    ],

    controller: 'divepanel',
    viewModel: {
        type: 'divepanel'
    },
    height: 419,
    width: 719,
    title: 'Dive Master',

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'button',
                    handler: 'DiverInButtonClick',
                    icon: '/images/download.png',
                    text: 'Diver In'
                },
                {
                    xtype: 'button',
                    handler: 'DiverOutButtonClick',
                    icon: '/images/up.png',
                    text: 'Diver Out'
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'button',
                    handler: 'newRunButtonClick',
                    icon: '/images/add.png',
                    text: 'New Run'
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'gridpanel',
            title: 'In The Water',
            store: 'ParticipantsStore',
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'DiverID',
                    text: 'Diver #'
                },
                {
                    xtype: 'gridcolumn',
                    width: 143,
                    dataIndex: 'DiverName',
                    text: 'Diver Name'
                },
                {
                    xtype: 'gridcolumn',
                    width: 165,
                    dataIndex: 'TeamName',
                    text: 'Team Name'
                },
                {
                    xtype: 'gridcolumn',
                    flex: 1,
                    dataIndex: 'StatusText',
                    text: 'Status Text'
                }
            ]
        }
    ]

});