/*
 * File: app/view/DivePanelMenu.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Admin.view.DivePanelMenu', {
    extend: 'Ext.menu.Menu',
    alias: 'widget.divepanelmenu',

    requires: [
        'Admin.view.DivePanelMenuViewModel',
        'Ext.menu.Separator'
    ],

    viewModel: {
        type: 'divepanelmenu'
    },

    items: [
        {
            xtype: 'menuitem',
            handler: function(item, e) {
                Ext.create('Admin.view.NewParticipant').show();
            },
            icon: '/images/up.png',
            text: 'Diver Out'
        },
        {
            xtype: 'menuseparator',
            text: 'Menu Item'
        },
        {
            xtype: 'menuitem',
            handler: function(item, e) {
                Ext.create('Admin.view.NewParticipant').show();
            },
            icon: '/images/add.png',
            text: 'View / Edit Participant'
        }
    ]

});