/*
 * File: app/view/NewParticipant.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Admin.view.NewParticipant', {
    extend: 'Ext.window.Window',
    alias: 'widget.newparticipant',

    requires: [
        'Admin.view.NewParticipantViewModel',
        'Admin.view.NewParticipantViewController',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Hidden'
    ],

    controller: 'newparticipant',
    viewModel: {
        type: 'newparticipant'
    },
    height: 248,
    margin: 5,
    padding: 5,
    width: 284,
    title: 'New Participant',

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'button',
                    handler: 'onSaveButtonClick',
                    icon: '/images/save.png',
                    text: 'Save'
                },
                {
                    xtype: 'button',
                    handler: function(button, e) {
                        this.up('window').close();
                    },
                    icon: '/images/delete.png',
                    text: 'Cancel'
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'form',
            id: 'NewParticipantForm',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'textfield',
                    width: 251,
                    fieldLabel: 'Name',
                    labelWidth: 75,
                    name: 'DiverName'
                },
                {
                    xtype: 'combobox',
                    fieldLabel: 'Team:',
                    labelWidth: 75,
                    name: 'TeamID',
                    displayField: 'TeamName',
                    store: 'TeamsStore',
                    valueField: 'uid'
                },
                {
                    xtype: 'combobox',
                    fieldLabel: 'Status:',
                    labelWidth: 75,
                    name: 'Status',
                    displayField: 'ListItem',
                    store: 'DiverStatusStore',
                    valueField: 'IntValue'
                },
                {
                    xtype: 'hiddenfield',
                    anchor: '100%',
                    id: 'NewParticipantSession',
                    fieldLabel: 'Label',
                    name: 'SID'
                }
            ]
        }
    ]

});