/*
 * File: app/view/OptionsPanel.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Admin.view.OptionsPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.optionspanel',

    requires: [
        'Admin.view.OptionsPanelViewModel',
        'Admin.view.OptionsPanelViewController',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.form.field.Hidden'
    ],

    controller: 'optionspanel',
    viewModel: {
        type: 'optionspanel'
    },
    defaultListenerScope: true,
    height: 510,
    padding: 5,
    width: 429,
    layout: 'fit',
    title: 'Options',

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'button',
                    handler: 'OnSaveButton',
                    icon: '/images/save.png',
                    text: 'Save',
                    scope: 'controller'
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'form',
            id: 'OptionsForm',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'textfield',
                    width: 159,
                    fieldLabel: 'ZipCode',
                    name: 'Zipcode'
                },
                {
                    xtype: 'textfield',
                    width: 159,
                    fieldLabel: 'FPS',
                    name: 'FPS'
                },
                {
                    xtype: 'textfield',
                    width: 159,
                    fieldLabel: 'Total Distance',
                    name: 'TotalDistance'
                },
                {
                    xtype: 'textfield',
                    width: 159,
                    fieldLabel: 'Time1 Distance',
                    name: 'Time1Distance'
                },
                {
                    xtype: 'textfield',
                    width: 159,
                    fieldLabel: 'Time2 Distance',
                    name: 'Time2Distance'
                },
                {
                    xtype: 'textfield',
                    width: 159,
                    fieldLabel: 'Time3 Distance',
                    name: 'Time3Distance'
                },
                {
                    xtype: 'textfield',
                    width: 159,
                    fieldLabel: 'Time4 Distance',
                    name: 'Time4Distance'
                },
                {
                    xtype: 'hiddenfield',
                    anchor: '100%',
                    id: 'OptionsSession',
                    fieldLabel: 'Label',
                    name: 'SID'
                }
            ]
        }
    ],
    listeners: {
        afterrender: 'onPanelAfterRender'
    },

    onPanelAfterRender: function(component, eOpts) {
        //load record
        var form = Ext.getCmp('OptionsForm').getForm();

        form.load({
            url: '/data/getjson.php',
            params: {
                dataset: 'options'
            },
            failure: function(form, action) {
                Ext.Msg.alert("Load failed", action.result.errorMessage);
            }
        });
    }

});