/*
 * File: app/view/Options.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Admin.view.Options', {
    extend: 'Ext.window.Window',
    alias: 'widget.options',

    requires: [
        'Admin.view.OptionsViewModel',
        'Admin.view.OptionsViewController',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Hidden'
    ],

    controller: 'options',
    viewModel: {
        type: 'options'
    },
    height: 510,
    margin: 5,
    padding: 5,
    width: 429,
    title: 'Options',

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'button',
                    handler: 'OnSaveButton',
                    icon: '/images/save.png',
                    text: 'Save'
                },
                {
                    xtype: 'button',
                    handler: function(button, e) {
                        this.up('window').close();
                    },
                    icon: '/images/delete.png',
                    text: 'Cancel'
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'form',
            id: 'OptionsForm',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'textfield',
                    width: 159,
                    fieldLabel: 'ZipCode',
                    name: 'Zipcode'
                },
                {
                    xtype: 'textfield',
                    width: 159,
                    fieldLabel: 'FPS',
                    name: 'FPS'
                },
                {
                    xtype: 'combobox',
                    fieldLabel: 'English/Metric',
                    name: 'MeasureMethod'
                },
                {
                    xtype: 'textfield',
                    width: 159,
                    fieldLabel: 'Total Distance',
                    name: 'TotalDistance'
                },
                {
                    xtype: 'textfield',
                    width: 159,
                    fieldLabel: 'Time1 Distance',
                    name: 'Time1Distance'
                },
                {
                    xtype: 'textfield',
                    width: 159,
                    fieldLabel: 'Time2 Distance',
                    name: 'Time2Distance'
                },
                {
                    xtype: 'textfield',
                    width: 159,
                    fieldLabel: 'Time3 Distance',
                    name: 'Time3Distance'
                },
                {
                    xtype: 'textfield',
                    width: 159,
                    fieldLabel: 'Time4 Distance',
                    name: 'Time4Distance'
                },
                {
                    xtype: 'hiddenfield',
                    anchor: '100%',
                    id: 'OptionsSession',
                    fieldLabel: 'Label',
                    name: 'SID'
                }
            ]
        }
    ]

});