/*
 * File: app/view/ParticipantsActivity.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Admin.view.ParticipantsActivity', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.participantsactivity',

    requires: [
        'Admin.view.ParticipantsActivityPanelViewModel',
        'Admin.view.ParticipantsActivityPanelController',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Number'
    ],

    controller: 'participantsactivity',
    viewModel: {
        type: 'participantsactivity'
    },
    height: 419,
    width: 719,
    layout: 'fit',
    title: 'Activity',
    defaultListenerScope: true,

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'button',
                    handler: 'downloadParticipantCSVButtonClicked',
                    href: '/data/exports/activityExport.php',
                    icon: '/images/download.png',
                    text: 'Download CSV',
                    scope: 'controller'
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'gridpanel',
            scrollable: 'both',
            store: 'ParticipantHistoryStore',
            listeners: {
                rowdblclick: 'RowDblClick',
                itemcontextmenu: 'onGridpanelItemContextMenu'
            },
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'DiverID',
                    text: 'Diver Id'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'ParticipantName',
                    text: 'Participant Name'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'TeamName',
                    text: 'Team Name'
                },
                {
                    xtype: 'gridcolumn',
                    flex: 1,
                    dataIndex: 'ActionText',
                    text: 'Action Text'
                },
                {
                    xtype: 'gridcolumn',
                    width: 107,
                    dataIndex: 'TrackedTime',
                    text: 'Tracked Time'
                },
                {
                    xtype: 'gridcolumn',
                    width: 157,
                    dataIndex: 'Timestamp',
                    text: 'Timestamp'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'RaceID',
                    text: 'Race Id'
                }
            ]
        }
    ],

    RowDblClick: function(tableview, record, tr, rowIndex, e, eOpts) {
        Ext.create('Admin.view.ViewParticipant').show();
    },

    onGridpanelItemContextMenu: function(dataview, record, item, index, e, eOpts) {
        e.stopEvent();
        selectedvalue = record.get('uid');
        selectedrec = record;
        popup = Ext.create('Admin.view.ParticipantsPanelMenu');
        popup.showAt(e.getXY());
    }

});