/*
 * File: app/view/ScoringPanel.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Admin.view.ScoringPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.scoringpanel',

    requires: [
        'Admin.view.ScoringPanelViewModel',
        'Admin.view.ScoringPanelViewController',
        'Ext.toolbar.Toolbar',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Number'
    ],

    controller: 'scoringpanel',
    viewModel: {
        type: 'scoringpanel'
    },
    height: 419,
    width: 719,
    title: 'Run Scoring',

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'button',
                    handler: 'onNewRunButtonClick',
                    icon: '/images/add.png',
                    text: 'New Run'
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'tabpanel',
            activeTab: 0,
            items: [
                {
                    xtype: 'panel',
                    title: 'New Runs',
                    items: [
                        {
                            xtype: 'gridpanel',
                            store: 'RacesStore',
                            columns: [
                                {
                                    xtype: 'numbercolumn',
                                    width: 70,
                                    dataIndex: 'RaceID',
                                    text: 'Race Id',
                                    format: '00'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 143,
                                    dataIndex: 'TeamName',
                                    text: 'Team Name'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 80,
                                    dataIndex: 'StartTime',
                                    text: 'Start Time'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 89,
                                    dataIndex: 'FinishTime',
                                    text: 'Finish Time'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 74,
                                    dataIndex: 'Time1',
                                    text: 'Time1'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 69,
                                    dataIndex: 'Time2',
                                    text: 'Time2'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 64,
                                    dataIndex: 'Time3',
                                    text: 'Time3'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 62,
                                    dataIndex: 'Time4',
                                    text: 'Time4'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'StatusText',
                                    text: 'Status'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'ClassText',
                                    text: 'Class'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'RaceDate',
                                    text: 'Race Date'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'Notes',
                                    text: 'Notes'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    title: 'Past Runs',
                    items: [
                        {
                            xtype: 'gridpanel',
                            store: 'RacesStore',
                            columns: [
                                {
                                    xtype: 'numbercolumn',
                                    width: 70,
                                    dataIndex: 'RaceID',
                                    text: 'Race Id',
                                    format: '00'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 143,
                                    dataIndex: 'TeamName',
                                    text: 'Team Name'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 80,
                                    dataIndex: 'StartTime',
                                    text: 'Start Time'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 89,
                                    dataIndex: 'FinishTime',
                                    text: 'Finish Time'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 74,
                                    dataIndex: 'Time1',
                                    text: 'Time1'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 69,
                                    dataIndex: 'Time2',
                                    text: 'Time2'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 64,
                                    dataIndex: 'Time3',
                                    text: 'Time3'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 62,
                                    dataIndex: 'Time4',
                                    text: 'Time4'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'StatusText',
                                    text: 'Status'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'ClassText',
                                    text: 'Class'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'RaceDate',
                                    text: 'Race Date'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'Notes',
                                    text: 'Notes'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});