/*
 * File: app/view/TeamsPanelMenu.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Admin.view.TeamsPanelMenu', {
    extend: 'Ext.menu.Menu',
    alias: 'widget.teamspanelmenu',

    requires: [
        'Admin.view.TeamsPanelMenuViewModel',
        'Ext.menu.Separator'
    ],

    viewModel: {
        type: 'teamspanelmenu'
    },
    height: 123,
    width: 192,

    items: [
        {
            xtype: 'menuitem',
            handler: function(item, e) {
                Ext.create('Admin.view.ViewParticipant').show();
            },
            icon: '/images/edit.png',
            text: 'View / Edit Team'
        },
        {
            xtype: 'menuseparator',
            text: 'Menu Item'
        },
        {
            xtype: 'menuitem',
            handler: function(item, e) {
                Ext.create('Admin.view.NewTeam').show();
            },
            icon: '/images/add.png',
            text: 'New Team'
        },
        {
            xtype: 'menuseparator',
            text: 'Menu Item'
        },
        {
            xtype: 'menuitem',
            icon: '/images/delete.png',
            text: 'Delete Team'
        }
    ]

});